### ISSUE TITLE
Errors when start docker-compose

### ISSUE THREAD

**Issue by lanmaster** [OsmHackTW/tiles-docker#3]
There is errors when start docker-compose:

[root@localhost osm-tiles-docker-master]# docker-compose up
Creating osm-tiles-docker-master_postgis_1_793be6a134c2 ... done
Creating osm-tiles-docker-master_web_1_1a31bf7f55b6       ... done
Creating osm-tiles-docker-master_osm2pgsql_1_1528604312f7 ... done
Attaching to osm-tiles-docker-master_postgis_1_450d772c3f96, osm-tiles-docker-master_osm2pgsql_1_beb8162aef80, osm-tiles-docker-master_web_1_eee0e1c6e04c
postgis_1_450d772c3f96 | LOG:  database system was interrupted; last known up at 2018-11-30 19:11:28 UTC
postgis_1_450d772c3f96 | LOG:  database system was not properly shut down; automatic recovery in progress
postgis_1_450d772c3f96 | LOG:  invalid record length at 0/1707650
postgis_1_450d772c3f96 | LOG:  redo is not required
postgis_1_450d772c3f96 | LOG:  MultiXact member wraparound protections are now enabled
postgis_1_450d772c3f96 | LOG:  database system is ready to accept connections
postgis_1_450d772c3f96 | LOG:  autovacuum launcher started
osm2pgsql_1_beb8162aef80 | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
osm2pgsql_1_beb8162aef80 | bash: no job control in this shell
osm2pgsql_1_beb8162aef80 | REGION=asia/taiwan
osm2pgsql_1_beb8162aef80 | COUNTRY=taiwan
osm2pgsql_1_beb8162aef80 | DATADIR=/osm
osm2pgsql_1_beb8162aef80 | PBF=/osm/taiwan-latest.osm.pbf
osm2pgsql_1_beb8162aef80 | LOOP=600
postgis_1_450d772c3f96 | FATAL:  no pg_hba.conf entry for host "172.19.0.4", user "postgres", database "postgres", SSL off
osm2pgsql_1_beb8162aef80 | psql: FATAL:  no pg_hba.conf entry for host "172.19.0.4", user "postgres", database "postgres", SSL off
web_1_eee0e1c6e04c | 2018-11-30 19:17:18,010 CRIT Set uid to user 0
web_1_eee0e1c6e04c | 2018-11-30 19:17:18,020 INFO RPC interface 'supervisor' initialized
web_1_eee0e1c6e04c | 2018-11-30 19:17:18,020 CRIT Server 'unix_http_server' running without any HTTP authentication checking
web_1_eee0e1c6e04c | 2018-11-30 19:17:18,021 INFO supervisord started with pid 1
web_1_eee0e1c6e04c | 2018-11-30 19:17:19,024 INFO spawned: 'renderd' with pid 7
web_1_eee0e1c6e04c | 2018-11-30 19:17:19,025 INFO spawned: 'apache2' with pid 8
web_1_eee0e1c6e04c | 2018-11-30 19:17:19,078 DEBG 'apache2' stderr output:
web_1_eee0e1c6e04c | [Fri Nov 30 19:17:19.076206 2018] [tile:warn] [pid 10:tid 140605000411008] Could not determine host name of server to configure tile-json request. Using localhost instead
web_1_eee0e1c6e04c | [Fri Nov 30 19:17:19.076271 2018] [tile:notice] [pid 10:tid 140605000411008] Loading tile config default at /osm_tiles/ for zooms 0 - 20 from tile directory /var/lib/mod_tile with extension .png and mime type image/png
web_1_eee0e1c6e04c | [Fri Nov 30 19:17:19.076278 2018] [tile:warn] [pid 10:tid 140605000411008] Could not determine host name of server to configure tile-json request. Using localhost instead
web_1_eee0e1c6e04c | [Fri Nov 30 19:17:19.076281 2018] [tile:notice] [pid 10:tid 140605000411008] Loading tile config osmcarto at /osmcarto/ for zooms 0 - 20 from tile directory /var/lib/mod_tile with extension .png and mime type image/png
web_1_eee0e1c6e04c | [Fri Nov 30 19:17:19.076290 2018] [tile:warn] [pid 10:tid 140605000411008] Could not determine host name of server to configure tile-json request. Using localhost instead
web_1_eee0e1c6e04c | [Fri Nov 30 19:17:19.076293 2018] [tile:notice] [pid 10:tid 140605000411008] Loading tile config osmbright at /osmbright/ for zooms 0 - 20 from tile directory /var/lib/mod_tile with extension .png and mime type image/png
web_1_eee0e1c6e04c | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | 2018-11-30 19:17:20,085 INFO success: renderd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1_eee0e1c6e04c | 2018-11-30 19:17:20,085 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1_eee0e1c6e04c | 2018-11-30 19:17:32,600 DEBG 'renderd' stdout output:
web_1_eee0e1c6e04c | installing to /usr/local/src/osm-bright/OSMBright
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | 2018-11-30 19:17:32,910 DEBG 'renderd' stderr output:
web_1_eee0e1c6e04c | [millstone] processing layer 'land-low'
web_1_eee0e1c6e04c | [millstone] processing layer 'land-high'
web_1_eee0e1c6e04c | [millstone] processing layer 'ne_places'
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | 2018-11-30 19:17:32,915 DEBG 'renderd' stderr output:
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-low/simplified_land_polygons.cpg' -> '/usr/local/src/osm-bright/shp/simplified-land-polygons-complete-3857/simplified_land_polygons.cpg'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-low/simplified_land_polygons.dbf' -> '/usr/local/src/osm-bright/shp/simplified-land-polygons-complete-3857/simplified_land_polygons.dbf'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-low/simplified_land_polygons.index' -> '/usr/local/src/osm-bright/shp/simplified-land-polygons-complete-3857/simplified_land_polygons.index'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-low/simplified_land_polygons.prj' -> '/usr/local/src/osm-bright/shp/simplified-land-polygons-complete-3857/simplified_land_polygons.prj'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-low/simplified_land_polygons.shp' -> '/usr/local/src/osm-bright/shp/simplified-land-polygons-complete-3857/simplified_land_polygons.shp'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-low/simplified_land_polygons.shx' -> '/usr/local/src/osm-bright/shp/simplified-land-polygons-complete-3857/simplified_land_polygons.shx'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-high/land_polygons.cpg' -> '/usr/local/src/osm-bright/shp/land-polygons-split-3857/land_polygons.cpg'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-high/land_polygons.dbf' -> '/usr/local/src/osm-bright/shp/land-polygons-split-3857/land_polygons.dbf'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-high/land_polygons.index' -> '/usr/local/src/osm-bright/shp/land-polygons-split-3857/land_polygons.index'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-high/land_polygons.prj' -> '/usr/local/src/osm-bright/shp/land-polygons-split-3857/land_polygons.prj'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-high/land_polygons.shp' -> '/usr/local/src/osm-bright/shp/land-polygons-split-3857/land_polygons.shp'
web_1_eee0e1c6e04c | [millstone] linking '/usr/local/src/osm-bright/OSMBright/layers/land-high/land_polygons.shx' -> '/usr/local/src/osm-bright/shp/land-polygons-split-3857/land_polygons.shx'
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | 2018-11-30 19:17:32,931 DEBG 'renderd' stderr output:
web_1_eee0e1c6e04c | /usr/local/lib/node_modules/millstone/node_modules/step/lib/step.js:39
web_1_eee0e1c6e04c |         throw arguments[0];
web_1_eee0e1c6e04c |         ^
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | Error: ENOENT: no such file or directory, scandir '/usr/local/src/osm-bright/shp/ne_10m_populated_places'
web_1_eee0e1c6e04c |     at Error (native)
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | 2018-11-30 19:17:33,221 DEBG 'renderd' stderr output:
web_1_eee0e1c6e04c | TypeError: Cannot read property 'Layer' of undefined
web_1_eee0e1c6e04c |     at Renderer.render (/usr/local/lib/node_modules/carto/lib/carto/renderer.js:116:26)
web_1_eee0e1c6e04c |     at compileMML (/usr/local/lib/node_modules/carto/bin/carto:87:31)
web_1_eee0e1c6e04c |     at Object.<anonymous> (/usr/local/lib/node_modules/carto/bin/carto:178:9)
web_1_eee0e1c6e04c |     at Module._compile (module.js:410:26)
web_1_eee0e1c6e04c |     at Object.Module._extensions..js (module.js:417:10)
web_1_eee0e1c6e04c |     at Module.load (module.js:344:32)
web_1_eee0e1c6e04c |     at Function.Module._load (module.js:301:12)
web_1_eee0e1c6e04c |     at Function.Module.runMain (module.js:442:10)
web_1_eee0e1c6e04c |     at startup (node.js:136:18)
web_1_eee0e1c6e04c |     at node.js:966:3
web_1_eee0e1c6e04c |
web_1_eee0e1c6e04c | 2018-11-30 19:17:33,229 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140417888024768 for <Subprocess at 140417896929832 with name renderd in state RUNNING> (stdout)>
web_1_eee0e1c6e04c | 2018-11-30 19:17:33,229 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 140417888024696 for <Subprocess at 140417896929832 with name renderd in state RUNNING> (stderr)>
web_1_eee0e1c6e04c | 2018-11-30 19:17:33,229 INFO exited: renderd (exit status 1; not expected)
web_1_eee0e1c6e04c | 2018-11-30 19:17:33,229 DEBG received SIGCLD indicating a child quit
web_1_eee0e1c6e04c | 2018-11-30 19:17:34,232 INFO spawned: 'renderd' with pid 94
web_1_eee0e1c6e04c | 2018-11-30 19:17:35,235 INFO success: renderd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by hitokiri** [comment]
Hello i have the same error

osmtiles_web | 
osmtiles_web | 2020-02-21 15:18:53,536 DEBG 'renderd' stderr output:
osmtiles_web | /usr/local/lib/node_modules/millstone/node_modules/step/lib/step.js:39
osmtiles_web |         throw arguments[0];
osmtiles_web |         ^
osmtiles_web | 
osmtiles_web | Error: ENOENT: no such file or directory, scandir '/usr/local/src/osm-bright/shp/ne_10m_populated_places'
osmtiles_web |     at Error (native)
osmtiles_web | 
osmtiles_web | 2020-02-21 15:18:53,816 DEBG 'renderd' stderr output:
osmtiles_web | TypeError: Cannot read property 'Layer' of undefined
osmtiles_web |     at Renderer.render (/usr/local/lib/node_modules/carto/lib/carto/renderer.js:116:26)
osmtiles_web |     at compileMML (/usr/local/lib/node_modules/carto/bin/carto:87:31)
osmtiles_web |     at Object.<anonymous> (/usr/local/lib/node_modules/carto/bin/carto:178:9)
osmtiles_web |     at Module._compile (module.js:410:26)
osmtiles_web |     at Object.Module._extensions..js (module.js:417:10)
osmtiles_web |     at Module.load (module.js:344:32)
osmtiles_web |     at Function.Module._load (module.js:301:12)
osmtiles_web |     at Function.Module.runMain (module.js:442:10)
osmtiles_web |     at startup (node.js:136:18)
osmtiles_web |     at node.js:966:3
osmtiles_web | 
osmtiles_web | 2020-02-21 15:18:53,819 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140180108341192 for <Subprocess at 140180117248480 with name renderd in state RUNNING> (stdout)>
osmtiles_web | 2020-02-21 15:18:53,820 DEBG fd 12 closed, stopped monitoring <POutputDispatcher at 140180108339248 for <Subprocess at 140180117248480 with name renderd in state RUNNING> (stderr)>
osmtiles_web | 2020-02-21 15:18:53,820 INFO exited: renderd (exit status 1; not expected)
osmtiles_web | 2020-02-21 15:18:53,820 DEBG received SIGCLD indicating a child quit
osmtiles_web | 2020-02-21 15:18:54,824 INFO spawned: 'renderd' with pid 431
osmtiles_web | 2020-02-21 15:18:55,827 INFO success: renderd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
osmtiles_web | 2020-02-21 15:19:08,136 DEBG 'renderd' stdout output:
osmtiles_web | installing to /usr/local/src/osm-bright/OSMBright
